fix: top array
Zubiik/pokedex pull request #26
Opened 2021-06-17 15:26 UTC by Zubiik

idk how to align text with stats

2021-06-20 17:14 UTC, shaftwin requested changes

2021-06-20 17:14 UTC, shaftwin commented on src/components/Stats/styled.js
>    flex-direction: column-reverse;
Enlève les deux column-reverse.
On va devoir remplacer l'algorythme du for.
On oublie pas la formule magique.
i < 15 - statDuPokemon

Good luck

2021-06-20 17:15 UTC, shaftwin commented
https://github.com/Zubiik/pokedex/blob/4ea9d916f39412cb0ff6129f6990fbf93db8a588/src/components/Stats/Index.js#L27

Tu peux enlever la <div></div> inutile

2021-06-21 12:05 UTC, Zubiik commented
> https://github.com/Zubiik/pokedex/blob/4ea9d916f39412cb0ff6129f6990fbf93db8a588/src/components/Stats/Index.js#L27
> 
> Tu peux enlever la
> inutile

pas compris

2021-06-22 12:59 UTC, shaftwin commented
> > https://github.com/Zubiik/pokedex/blob/4ea9d916f39412cb0ff6129f6990fbf93db8a588/src/components/Stats/Index.js#L27
> > 
> > Tu peux enlever la
> > inutile
> 
> pas compris

Tu peux supprimer la div autour de <Item>

2021-06-23 12:54 UTC, shaftwin approved these changes

2021-06-23 13:38 UTC, merged